# add logging and health check
services:
  backend:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chattools_db
      - SPRING_DATASOURCE_USERNAME=REPLACE
      - SPRING_DATASOURCE_PASSWORD=REPLACE
    env_file:
      - ./chattools-backend/.env
    depends_on:
      - db
    container_name: chattools-backend
    networks:
      - caddy-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=chattools_db
      - POSTGRES_USER=${CHATTOOLS_DB_USER}
      - POSTGRES_PASSWORD=${CHATTOOLS_DB_PASSWORD}
    volumes:
      - chattools_db:/var/lib/postgresql/data

  frontend:
    # ports:
    #   - "5173:5173"
    container_name: chattools-frontend
    networks:
      - caddy-network

volumes:
  caddy-config:
  caddy-data:
  chattools_db:

networks:
  caddy-network:
    name: caddy-network
    external: true
