# add logging and health check
services:
  backend:
    build:
      context: ./chattools-backend
    ports:
      - 8080:8080
    env_file:
      - ./chattools-backend/.env
  
  caddy:
    build:
      context: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      - CADDY_ENV=prod
      - DOMAIN_NAME=${DOMAIN_NAME}

volumes:
  caddy-config:
  caddy-data: