server:
  servlet:
    session:
      timeout: 30d

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: authorization_code
            client-name: twitch
            client-id: ${TWITCH_OAUTH_CLIENT_ID}
            client-secret: ${TWITCH_OAUTH_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/login/oauth2/callback/{registrationId}"
            scope:
              - openid
              - user:read:email
            provider: twitch
        provider:
          twitch:
            issuer-uri: https://id.twitch.tv/oauth2

  config:
    import: optional:file:.env[.properties]

#debug: true
#logging:
#  level:
#    org:
#      springframework:
#        security: trace